### ISSUE TITLE
Type: AWS::SQS::Queue -  DeletionPolicy is required. But it's not true

### ISSUE THREAD

**Issue by realtebo** [aws-cloudformation/cfn-lint-visual-studio-code#434]
I've this resource 

```
Type: AWS::SQS::Queue
```

The linter is yelling at me: 

> [cfn-lint] I3011: 'DeletionPolicy' is a required property (The default action when replacing/removing a resource is to delete it. Set explicit values for stateful resource)

But see here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html

This property is not even listed. So it cannot be required

**Comment by kddejong** [comment]
Its an Informational level error so you can choose to ignore this. If you choose to not ignore this issue... because SQS queues can have data in them we recommend setting a [DeletionPolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html) and an [UpdateReplacePolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html) that will make your intentions clear about how you want CloudFormation to handle this resource if it needs to be replaced or deleted.  I would read the included docs to see what option works the best for your use case. 

```yaml
Resources:
  Queue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      ....
```
